// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
public class MainGUI : MonoBehaviour
{
		private GUIStyle style;
		void Start ()
		{
				style = new GUIStyle ();
				style.fontSize = 30;
		}
	
		// Update is called once per frame
		void Update ()
		{
		
		}
	
		void OnGUI ()
		{

			
			
				float bWidth = UnityEngine.Screen.width / 5;
				float bHeight = UnityEngine.Screen.height / 3;
				if (GUI.Button (new Rect (Screen.width - bWidth, Screen.height - bHeight, bWidth, bHeight), "next")) {
						Model.curCarIndex++;
						checkCar ();
						(ScreenManager.getCurScreen () as StartMenuScreen).changeCar ();
				}
			
				if (GUI.Button (new Rect (0, Screen.height - bHeight, bWidth, bHeight), "prew")) {
						Model.curCarIndex--;
						checkCar ();
						(ScreenManager.getCurScreen () as StartMenuScreen).changeCar ();
				}
			
				if (GUI.Button (new Rect (Screen.width / 2 - bWidth / 2, 0, bWidth, bHeight), "S T A R T")) {
						ScreenManager.showScreen (ScreenManager.Screens.GAME);
				}
			

		}
		void checkCar ()
		{
				if (Model.curCarIndex < 0)
						Model.curCarIndex = Model.cars.Length - 1;

				if (Model.curCarIndex >= Model.cars.Length)
						Model.curCarIndex = 0;
		}
}




