// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
	public class MainGUI : MonoBehaviour
		{
				public MainGUI ()
				{
				}

		void OnGUI () {

			
			
			float bWidth = UnityEngine.Screen.width / 5;
			float bHeight = UnityEngine.Screen.height / 3;
			if (GUI.RepeatButton(new Rect (Screen.width - bWidth,Screen.height - bHeight,bWidth,bHeight), "accelerate")) {

			}
			
			if (GUI.RepeatButton (new Rect (0,Screen.height - bHeight,bWidth,bHeight), "breake")) {

			}
			

			

		}
		}




